### ISSUE TITLE
final ToDo

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/Rintro#78]
- [x] Send reminder email to participants
- [x] check workbench: R-version, package installation, git clone) 
- [x] Check QR code
- [x] Check polleverywhere: https://pollev.com/thomasmanke101
- [x] check that emergency .libPaths is in place (/scratch/local/rintro/) and up-to-date
- [x] check /scratch/local sufficient space
